### ISSUE TITLE
中间件配置问题

### ISSUE THREAD

**Issue by dongm2ez** [LingxiTeam/laravel-hashids#1]
中间件配置在 $middleware = [] 中 $request->route() 拿不到任何东西，我是5.4版本，
必须配置$middlewareGroups 中的 api 或者 web 中

这里有相关描述
http://stackoverflow.com/questions/31868759/request-route-is-null-in-middleware-how-can-i-filter-by-route-parameters

**Comment by sword-jin** [comment]
@dongm2ez 确实存在这个问题，laravel 在处理全局中间件还没有启动路由，所以这个时候无法处理路由参数，那么只能手动注册了
