### ISSUE TITLE
PublicId 疑问

### ISSUE THREAD

**Issue by dongm2ez** [LingxiTeam/laravel-hashids#2]
ModelTraits/PublicId.php 中的 getHashIdsConnection 在 Hashids.php 只一个继承方法，在PublicId.php 中是怎么调用到的

**Comment by sword-jin** [comment]
@dongm2ez 这是之前发布到 github 上修改命名辅助方法造成的 bug

https://github.com/LingxiTeam/laravel-hashids/commit/f90014fd816a2a68918f0fda1d6dd9bcef4bb850

**Comment by sword-jin** [comment]
@dongm2ez 我今天把几个项目的依赖换到 github 上了，目前都跑得 5.3，没有出现任何问题
