### ISSUE TITLE
中间件 trueId 问题

### ISSUE THREAD

**Issue by dongm2ez** [LingxiTeam/laravel-hashids#3]
case 0 时，返回 null，这时候 null 值传递给路由解析就会产生 Internal error: Failed to retrieve the default value 错误

这是我预期得到的 404 的错误，但还没传到控制器框架以及报错了，这里的情况应该是没有解析到对应的trueid 返回一个无法在数据库中查到的值应该就可以了，而不是返回null引起框架报错

**Comment by sword-jin** [comment]
```
if (is_array($id)) {
            switch (count($id)) {
                case 0:
                    return null;

                case 1:
                    return $id[0];

                default:
                    return $id;
            }
        } else {
            return null;
        }
```

因为 hashids 可以对数组进行加密，我们的使用场景大部分都是加密单个数，所以解密出来的数组在正确的情况下应该返回一个长度为 1 的数组。

对于返回 null，我觉得处理的时候就抛出异常，对于是否应该在这里去做异常处理，需要考虑一下。

比如中间件中这样处理

```
public function handleTrueId($trueId)
    {
        if ($trueId === null) {
            throw new ApiErrorException(ErrorType::PARAMETER_PARSE_ERROR);
        }
    }
```

不过你说的这个方案，我下次更新会采用，谢谢指出，确实应该在更底层的地方去抛出异常。

**Comment by sword-jin** [comment]
已处理 https://github.com/LingxiTeam/laravel-hashids/commit/20a96c7b4fe10097a77afeebd090e0a552b071b8
