### ISSUE TITLE
文档笔误

### ISSUE THREAD

**Issue by yuzewang** [LingxiTeam/laravel-hashids#5]
https://github.com/LingxiTeam/laravel-hashids/blob/master/README.md
php artisan vendor:public --provider='Lingxi\Hashids\HashidsServiceProvider'
应为vendor:publish

**Comment by yuzewang** [comment]
config/hashids.php
'connections' => [

        'main' => [
            'salt' => env('HASHIDS_MAIN_LENGTH', 'your-salt-string'),
            'length' => env('HASHIDS_MAIN_LENGTH', 'your-length-integer'),
        ],

        'alternative' => [
            'salt' => env('HASHIDS_ALTERNATIVE_LENGTH', 'your-salt-string'),
            'length' => env('HASHIDS_ALTERNATIVE_LENGTH', 'your-length-integer'),
        ],

    ],

应为

'connections' => [

        'main' => [
            'salt' => env('**HASHIDS_MAIN_SALT**', 'your-salt-string'),
            'length' => env('HASHIDS_MAIN_LENGTH', 'your-length-integer'),
        ],

        'alternative' => [
            'salt' => env('**HASHIDS_ALTERNATIVE_SALT**', 'your-salt-string'),
            'length' => env('HASHIDS_ALTERNATIVE_LENGTH', 'your-length-integer'),
        ],

    ],

**Comment by sword-jin** [comment]
@yuzewang  嗯，3Q
