### ISSUE TITLE
php artisan id:de  Class 'Lingxi\Hashids\Console\Commands\Hashids' not found

### ISSUE THREAD

**Issue by yuzewang** [LingxiTeam/laravel-hashids#6]
php artisan id:en 2
Give you a secret, go your browser.
or

php artisan id:de or
Give you a true id.
 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Lingxi\Hashids\Console\Commands\Hashids' not found

**Comment by sword-jin** [comment]
上次把 public_id 和 true_id 辅助方法，移出核心逻辑，忘记命名空间了
